# general configuration
url: https://havluj.eu

template:
  logo: "/images/picture.jpg"
  author: "Jan Havluj"
  tagline: "SDE at Amazon"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "docker-compose.yml"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
